Update pipeline-ci.yml

diff --git a/.github/workflows/pipeline-ci.yml b/.github/workflows/pipeline-ci.yml
--- a/.github/workflows/pipeline-ci.yml
+++ b/.github/workflows/pipeline-ci.yml
@@ -51,32 +51,45 @@ jobs:
     - name: Build
       id: build
       run: |
-            pwd
-            ls -R
+          pwd
+          ls -R
 
-            if [ -f "package.json" ]; then
-              echo "Utiliza package.json, proyecto Node.js o React"
-              echo "Instalando dependencias"
-              npm install
+          if [ -f "package.json" ]; then
+            echo "Utiliza package.json, proyecto Node.js o React"
+            echo "Instalando dependencias"
+            npm install
 
-              if grep -q '"vite"' package.json; then
-              echo "Construyendo proyecto con Vite y TypeScript"
-              npm run build  # Este comando ejecutará 'tsc' y 'vite build'
+          if grep -q '"vite"' package.json; then
+             echo "Construyendo proyecto con Vite y TypeScript"
+             npm run build  # Este comando ejecutará 'tsc' y 'vite build'
 
-              if [ -d "build" ] && [ "$(ls -A build)" ]; then
-              mkdir -p ${{ github.workspace }}/build
-              cp -r build/* ${{ github.workspace }}/build
-            else
-              echo "El directorio 'build/' está vacío o no existe después de construir."
-              exit 1  # Terminar el script con error si no hay archivos en build/
-            fi
-            else
-              echo "El proyecto no utiliza Vite o TypeScript según package.json."
-              exit 1  # Terminar el script con error si no se encuentra Vite en package.json
-            fi
-            else
-            echo "Otro tipo de proyecto"
-            fi
+             echo "Archivos y directorios antes de la construcción:"
+             ls -l ${{ github.workspace }}
+
+          if [ -d "build" ] && [ "$(ls -A build)" ]; then
+             mkdir -p ${{ github.workspace }}/build
+             cp -r build/* ${{ github.workspace }}/build
+
+            echo "Archivos y directorios creados despues de la construccion"
+           ls -l ${{ github.workspace }}
+
+          # Mostrar archivos y directorios que existen en el directorio raíz después de la construcción
+          echo "Archivos y directorios en el directorio raíz después de la construcción:"
+          ls -l ${{ github.workspace }}
+          else
+          echo "El directorio 'build/' está vacío o no existe después de construir."
+          echo "Contenido actual de 'build/':"
+          ls -l build  # Mostrar contenido de build/ si existe pero está vacío
+          exit 1  # Terminar el script con error si no hay archivos en build/
+          fi
+          else
+          echo "El proyecto no utiliza Vite o TypeScript según package.json."
+          exit 1  # Terminar el script con error si no se encuentra Vite en package.json
+          fi
+          else
+          echo "Otro tipo de proyecto"
+          fi
+
 
 
     - name: Update Dependencies
