Update pipeline-ci.yml

diff --git a/.github/workflows/pipeline-ci.yml b/.github/workflows/pipeline-ci.yml
--- a/.github/workflows/pipeline-ci.yml
+++ b/.github/workflows/pipeline-ci.yml
@@ -38,6 +38,20 @@ jobs:
           -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.branch.name=feature-Alberto-Verdugo-Ponce-Laboratorio-Final
 
+    - name: Check SonarCloud Quality Gate
+      run: |
+          PROJECT_KEY=ALBERTOVERDUGO_Laboratorio-final
+          ORGANIZATION=albertoverdugo
+          SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
+          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/project_branches/list?project=${PROJECT_KEY}" | jq -r '.branches[] | select(.name=="feature-Alberto-Verdugo-Ponce-Laboratorio-Final") | .status.qualityGateStatus')
+
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+          echo "Quality gate failed: $QUALITY_GATE_STATUS"
+          exit 1
+          else
+          echo "Quality gate passed: $QUALITY_GATE_STATUS"
+          fi
+
 #SCA -------------------------------------------
 
   SCA:
